# PostgreSQL Config
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/batch_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        type:
          wrapper_array_handling: ALLOW